# NAME: AdobeActivation
# AUTHOR: 互联网
# REPO: https://macwk.cn + https://github.com/blackmatrix7/ios_rule_script/tree/master/rule/QuantumultX/AdobeActivation
# UPDATED: 不定时
# HOST: 191
# IP-CIDR: 41
# host-keyword：4
# TOTAL: 236

# 一、adobe.com 精准过滤 161条
HOST,adobeid-na1.services.adobe.com,AdobeActivation
HOST,auth.services.adobe.com,AdobeActivation
HOST,activate-sea.adobe.com,AdobeActivation
HOST,activate-sjc0.adobe.com,AdobeActivation
HOST,activate.adobe.com,AdobeActivation
HOST,3dns-1.adobe.com,AdobeActivation
HOST,3dns-2.adobe.com,AdobeActivation
HOST,3dns-3.adobe.com,AdobeActivation
HOST,3dns-4.adobe.com,AdobeActivation
HOST,3dns-5.adobe.com,AdobeActivation
HOST,3dns.adobe.com,AdobeActivation
HOST,activate.wip.adobe.com,AdobeActivation
HOST,activate.wip1.adobe.com,AdobeActivation
HOST,activate.wip2.adobe.com,AdobeActivation
HOST,activate.wip3.adobe.com,AdobeActivation
HOST,activate.wip4.adobe.com,AdobeActivation
HOST,www.wip.adobe.com,AdobeActivation
HOST,www.wip1.adobe.com,AdobeActivation
HOST,www.wip2.adobe.com,AdobeActivation
HOST,www.wip3.adobe.com,AdobeActivation
HOST,www.wip4.adobe.com,AdobeActivation
HOST,adobe-dns-1.adobe.com,AdobeActivation
HOST,adobe-dns-2.adobe.com,AdobeActivation
HOST,adobe-dns-3.adobe.com,AdobeActivation
HOST,adobe-dns-4.adobe.com,AdobeActivation
HOST,adobe-dns.adobe.com,AdobeActivation
HOST,adobe.activate.com,AdobeActivation
HOST,cc-cdn.adobe.com,AdobeActivation
HOST,cc-cdn.adobe.com.edgekey.net,AdobeActivation
HOST,cclibraries-defaults-cdn.adobe.com,AdobeActivation
HOST,cclibraries-defaults-cdn.adobe.com.edgekey.net,AdobeActivation
HOST,cmdls.adobe.com,AdobeActivation
HOST,crlog-crcn.adobe.com,AdobeActivation
HOST,crs.cr.adobe.com,AdobeActivation
HOST,ereg.adobe.com,AdobeActivation
HOST,ereg.wip.adobe.com,AdobeActivation
HOST,ereg.wip1.adobe.com,AdobeActivation
HOST,ereg.wip2.adobe.com,AdobeActivation
HOST,ereg.wip3.adobe.com,AdobeActivation
HOST,ereg.wip4.adobe.com,AdobeActivation
HOST,genuine.adobe.com,AdobeActivation
HOST,geo2.adobe.com,AdobeActivation
HOST,hl2rcv.adobe.com,AdobeActivation
HOST,hlrcv.stage.adobe.com,AdobeActivation
HOST,lm.licenses.adobe.com,AdobeActivation
HOST,lmlicenses.wip4.adobe.com,AdobeActivation
HOST,na1r.services.adobe.com,AdobeActivation
HOST,na2m-pr.licenses.adobe.com,AdobeActivation
HOST,na2m-stg2.licenses.adobe.com,AdobeActivation
HOST,na4r.services.adobe.com,AdobeActivation
HOST,practivate.adobe.com,AdobeActivation
HOST,prod-rel-ffc-ccm.oobesaas.adobe.com,AdobeActivation
HOST,s-2.adobe.com,AdobeActivation
HOST,s-3.adobe.com,AdobeActivation
HOST,ssl-delivery.adobe.com.edgekey.net,AdobeActivation
HOST,sstats.adobe.com,AdobeActivation
HOST,stls.adobe.com-cn.edgesuite.net,AdobeActivation
HOST,stls.adobe.com-cn.edgesuite.net.globalredir.akadns.net,AdobeActivation
HOST,uds.licenses.adobe.com,AdobeActivation
HOST,use-stls.adobe.com.edgesuite.net,AdobeActivation
HOST,wip.adobe.com,AdobeActivation
HOST,wip1.adobe.com,AdobeActivation
HOST,wip2.adobe.com,AdobeActivation
HOST,wip3.adobe.com,AdobeActivation
HOST,wip4.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip30.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip31.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip32.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip33.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip34.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip35.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip36.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip37.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip38.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip39.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip40.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip41.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip42.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip43.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip44.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip45.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip46.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip47.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip48.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip49.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip50.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip51.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip52.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip53.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip54.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip55.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip56.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip57.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip58.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip59.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip60.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip61.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip62.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip63.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip64.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip65.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip66.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip67.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip68.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip69.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip70.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip71.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip72.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip73.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip74.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip75.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip76.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip77.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip78.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip79.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip80.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip81.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip82.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip83.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip84.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip85.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip86.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip87.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip88.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip89.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip90.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip91.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip92.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip93.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip94.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip95.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip96.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip97.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip98.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip99.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip100.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip101.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip102.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip103.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip104.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip105.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip106.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip107.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip108.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip109.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip110.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip111.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip112.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip113.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip114.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip115.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip116.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip117.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip118.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip119.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip120.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip121.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip122.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip123.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip124.adobe.com,AdobeActivation
HOST,wwis-dubc1-vip125.adobe.com,AdobeActivation

# 二、杂鱼补充 30条
HOST,adobe.demdex.net,AdobeActivation
HOST,adobedc.demdex.net,AdobeActivation
HOST,adobe.tt.omtrdc.net,AdobeActivation
HOST,adobeereg.com,AdobeActivation
HOST,assets.adobedtm.com,AdobeActivation
HOST,auth-cloudfront.prod.ims.adobejanus.com,AdobeActivation
HOST,bam.nr-data.net,AdobeActivation
HOST,crl.verisign.net,AdobeActivation
HOST,crl.verisign.net.,AdobeActivation
HOST,cn-assets.adobedtm.com.edgekey.net,AdobeActivation
HOST,ethos.ethos02-prod-irl1.ethos.adobe.net,AdobeActivation
HOST,ims-na1-prprod.adobelogin.com,AdobeActivation
HOST,k.sni.global.fastly.net,AdobeActivation
HOST,ood.opsource.net,AdobeActivation
HOST,practivate.adobe,AdobeActivation
HOST,practivate.adobe.,AdobeActivation
HOST,practivate.adobe.ipp,AdobeActivation
HOST,practivate.adobe.newoa,AdobeActivation
HOST,practivate.adobe.ntp,AdobeActivation
HOST,prod.adobegenuine.com,AdobeActivation
HOST,services.prod.ims.adobejanus.com,AdobeActivation
HOST,tss-geotrust-crl.thawte.com,AdobeActivation
HOST,workflow-ui-prod.licensingstack.com,AdobeActivation
HOST,www.adobeereg.com,AdobeActivation
HOST,paddleapi.com,AdobeActivation
HOST,paddle.com,AdobeActivation
HOST,paddle.s3.amazonaws.com,AdobeActivation
HOST,registration.presonus.com,AdobeActivation
HOST,updates.presonus.com,AdobeActivation
HOST,api.presonus.com,AdobeActivation

# 三、IP-CIDR 41条
IP-CIDR,3.208.248.199/32,AdobeActivation
IP-CIDR,3.216.32.253/32,AdobeActivation
IP-CIDR,3.219.243.226/32,AdobeActivation
IP-CIDR,3.220.11.113/32,AdobeActivation
IP-CIDR,3.221.72.231/32,AdobeActivation
IP-CIDR,13.227.103.57/32,AdobeActivation
IP-CIDR,18.228.243.121/32,AdobeActivation
IP-CIDR,18.230.164.221/32,AdobeActivation
IP-CIDR,23.22.30.141/32,AdobeActivation
IP-CIDR,34.192.151.90/32,AdobeActivation
IP-CIDR,34.215.42.13/32,AdobeActivation
IP-CIDR,34.237.241.83/32,AdobeActivation
IP-CIDR,44.240.189.42/32,AdobeActivation
IP-CIDR,52.6.155.20/32,AdobeActivation
IP-CIDR,52.10.49.85/32,AdobeActivation
IP-CIDR,52.20.222.155/32,AdobeActivation
IP-CIDR,52.84.156.37/32,AdobeActivation
IP-CIDR,52.208.86.132/32,AdobeActivation
IP-CIDR,54.156.135.114/32,AdobeActivation
IP-CIDR,54.208.86.132/32,AdobeActivation
IP-CIDR,54.221.228.134/32,AdobeActivation
IP-CIDR,54.224.241.105/32,AdobeActivation
IP-CIDR,63.140.38.120/32,AdobeActivation
IP-CIDR,63.140.38.160/32,AdobeActivation
IP-CIDR,63.140.38.169/32,AdobeActivation
IP-CIDR,63.140.38.219/32,AdobeActivation
IP-CIDR,65.8.207.109/32,AdobeActivation
IP-CIDR,100.24.211.130/32,AdobeActivation
IP-CIDR,162.247.242.20/32,AdobeActivation
IP-CIDR,199.232.114.137/32,AdobeActivation
IP-CIDR,192.150.14.69,AdobeActivation
IP-CIDR,192.150.18.101,AdobeActivation
IP-CIDR,192.150.18.108,AdobeActivation
IP-CIDR,192.150.22.40,AdobeActivation
IP-CIDR,192.150.8.100,AdobeActivation
IP-CIDR,192.150.8.118,AdobeActivation
IP-CIDR,199.7.52.190,AdobeActivation
IP-CIDR,199.7.52.190:80,AdobeActivation
IP-CIDR,199.7.54.72,AdobeActivation
IP-CIDR,199.7.54.72:80,AdobeActivation
IP-CIDR,prod.adobegenuine.com,AdobeActivation

# 四、别来沾边 4条
host-keyword,adobe.de,AdobeActivation
host-keyword,adobe.io,AdobeActivation
host-keyword,adobestats.io,AdobeActivation
host-keyword,hstatic.io,AdobeActivation
